name: Build PVE image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run bash script
        run: | 
          sudo apt install debootstrap squashfs-tools xorriso -y
          sudo bash build.sh clean
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: Proxmox ISO
          path: /tmp/tempdir/proxmox*.iso

