name: Build PVE image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run bash script
        run: | 
          sudo apt install debootstrap squashfs-tools  xorriso -y
          sudo bash build.sh clean 
