name: Build PVE image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run bash script
        run: apt install debootstrap squashfs-tools  xorriso -y && bash build.sh clean 
